#! /bin/bash

# Seeks the description of the given command options

usage () {
	echo "Usage: $(basename $0) [OPTION]... [COMMAND] [COMMAND OPTIONS]..." 2>/dev/null 
	echo "Seek information about command options"
	echo "Example: $(basename $0) -l grep -E -P" 
	echo
	echo " -l long answer"
	echo " -s short answer (default)"
	echo " -h display this message"
	echo
	echo "Command options must be separated (example: -a -b --auth ...)."
}

#######################################
# Seeks the option description using --help o -h
# Globals:
#   COMMAND
# Arguments:
#   option
# Returns:
# 	Command description in short format if found
# 	Code 2 if not found
#######################################
seek_short () {
	local option
	option=$1

	# Tries to get the option information, first with --help,
	# then with -h. If something is found, prints the ouput.
	# If nothing found exits with 2
	help_output=$($COMMAND --help 2>/dev/null | grep -P "^[ ]+$option")
	if [[ $? -ne 0 ]]; then
		h_output=$($COMMAND -h 2>/dev/null | grep -P "^[ ]+$option")
		{ [[ $? -ne 0 ]] && exit 2; } \
		|| printf "%s" "$h_output";
	else
		printf "%s" "$help_output"
	fi
}

#######################################
# Seeks the option description using man pages
# Globals:
#   COMMAND
# Arguments:
#   option
# Returns:
# 	Command description in large format if found
# 	Code 2 if not found
#######################################
seek_long () {
	local option
	option=$1

	# if the man page of the command has a OPTION section, use it as beginning
	# of the search, otherwise use DESCRIPTION
	man $COMMAND | grep -P "^OPTIONS$" &>/dev/null
	if [[ $? -eq 0 ]]; then
		ceil="OPTIONS"
	else
		ceil="DESCRIPTION"
	fi

	# Gets the end of the wanted_section selection wherein the search
	# is going to be
	floor=$(man $COMMAND \
	  | grep -P "^[A-Z ]+$" \
	  | grep $ceil -A 1 \
	  | tail -n 1 | xargs)

	# Extract from the man page only the section that contains the options
	# descriptions then chops it leaving at the top the option passed
	# and removes the last line that contains the following option
	wanted_section=$(man $COMMAND \
	  | awk "/^$ceil$/,/^$floor$/" \
	  | awk "/^[ ]+$option/,/^$floor/" \
	  | head -n -1)

	# Gets the minimum identation, that is the identation of the current option,
	# in order to get all its description. A smaller identation means a 
	# description of something else
	# NOT WORKED:
	#   1. tried to get the description by delimiting by opitions
	#     (as with ceil and floor) but with some options it did't work properly
	min_identation=$(printf "%s" "$wanted_section" \
	  | grep -P "^[ ]+$option" \
	  | head -n 1 \
	  | tr " " "*" \
	  | cut -d "-" -f 1 \
	  | wc -c)

	description=$(head -n 1 <<< $wanted_section)
	end=""
	# Go line by line checking identation
	while IFS= read -r line; do
		ident=0
		# Replaces spaces by * in order to count them and get the line's identation
		modified_line=$(tr " " "*" <<< $line)
		for (( i=0; i<${#modified_line}; i++ )); do
			# Only count the * that represent identation
			{ [[ "${modified_line:$i:1}" == "*" ]] && ((ident+=1)); } || break
		done

		# Finds the end of the description by finding the line in which the
		# identation is smaller than the min_identation
		# If it's an empty line does not count it, but don't take as end either
		if [[ $ident -gt $min_identation ]]; then
			end=$(sed 's/[-.\\\[{}()*+?\\^$|\/#]/\\&/g' <<< $line)
		elif [[ $ident -eq 0 ]]; then
			continue
		else
			break
		fi
	done <<< "$(tail -n +2 <<< $wanted_section)"  # pass each line but the wanted option
	long_desc=$(man $COMMAND | awk "/^[ ]+$option/, /$end/")

	{ [[ $? -ne 0 ]] && exit 2; } \
	|| printf "%s" "$long_desc"

}


###############################################################################
# Body
###############################################################################

if [[ ${#} -eq 0 ]]; then
	usage
	exit 1
fi

optstring=":lsh"
# Three possible options for LONG_OPT:
# true (-l) -> seeks given options within manual pages
# false (-s) -> seeks given options using --help or -h (if the first one fails)
#   of the specified command
# both (default) -> first seeks using --help, if it fails, it uses -h,
#   if it also fails, tries with man
LONG_OPT='both'

while getopts ${optstring} arg; do
	case ${arg} in
		l)
			LONG_OPT='true'
			;;
		s) 
			LONG_OPT='false'
			;;
		h)
			usage
			exit 0
			;;
		?)
			echo "Invalid option: -${OPTARG}."
			echo
			usage
			exit 1
			;;
	esac
done

shift $((OPTIND - 1))  # ${@} contains the non-option arg
COMMAND=$1
# gets each option passed, with dashed scaped \-
read -ra options <<< $(sed "s/\-/\\\-/g" <<< ${@:2})
#echo "command: $COMMAND, options: ${options[@]}"

# ---
# Loop through all the options to obtain its information
# ---
for option in ${options[@]}; do
	if [[ $LONG_OPT == "false" ]] || [[ $LONG_OPT == "both" ]]; then
		seek_short "$option"
		{ [[ $? -ne 0 ]] \
		&& echo "Nothing found" \
		&& exit 2; } \
		|| echo 

	elif [[ $LONG_OPT == "true" ]] || [[ $LONG_OPT == "both" ]]; then
		seek_long "$option"
		{ [[ $? -ne 0 ]] \
		&& echo "Nothing found" \
		&& exit 2; } \
		|| echo 
	fi
done

